import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { supabase } from './api/supabaseClient'

export default function Home({ Boats }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Sailboat Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>All Boats</h1>
        {console.log(Boats)}
        {Boats?.map(boat_page => (
          <Link key={boat_page.id} href={"/boat-pages/"+boat_page["Boat Name"]}>
            <a className={styles.link}>
              <h3>{boat_page["Boat Name"]}</h3>
            </a>
          </Link>
        ))}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await supabase
    .from('Boats')
    .select()
  const data = await res.data
  return {
    props: { Boats: data }
  }
}
